export const links = [
    "Sign Up",
    "Log In",
    "Messenger",
    "Facebook Lite",
    "Video",
    "Places",
    "Games",
    "Meta AI",
    "Instagram",
    "Threads",
    "Fundraisers",
    "Services",
    "Voting Information Center",
    "Privacy Policy",
    "Privacy Center",
    "Cookie Settings",
    "Groups",
    "About",
    "Create ad",
    "Create Page",
    "Developers",
    "Careers",
    "Cookies",
    "Ad choices",
    "Terms",
    "Help",
    "Contact Uploading & Non-Users",
    "Settings",
    "Activity log"
  ];
  